### ISSUE TITLE
DAO/Organization members not showing up

### ISSUE THREAD

**Issue by leeduckgo** [WeLightProject/Tai-Shang-Soul-Card#116]
![image](https://user-images.githubusercontent.com/12784118/190852524-2d39ddb1-a075-43f5-88ae-bd0d0ee6f38a.png)

**Comment by Dream4ever** [comment]
![image](https://user-images.githubusercontent.com/2596367/190855081-b857e7fc-33bd-4826-8ce0-5b0214d2685a.png)
