### ISSUE TITLE
CodesOnChain.TemplateManager.ex

### ISSUE THREAD

**Issue by snowyaya** [WeLightProject/Tai-Shang-Soul-Card#15]
Create a TemplateMangaer, authority by Ethereum signature, and save a key-value pair in K-V Table.
1) put(template_gist_id, msg, signature)
k: v = %{templates: [gist_id_1, gist_id_2, gist_id_3]}

2) get() 
returns the list of gist_id, e.g., [gist_id_1, gist_id_2, gist_id_3]

**Comment by leeduckgo** [comment]
G00D
