### ISSUE TITLE
关于本项目设计 Snippets & Componets 的源码分析。

### ISSUE THREAD

**Issue by leeduckgo** [WeLightProject/Tai-Shang-Soul-Card#28]
https://gist.github.com/leeduckgo/9813ca9e206bbda1afb413ecea331063

拆分为 3 篇文章，每篇文章 600R

**Comment by zhenfeng-zhu** [comment]
🙋🏻‍♂️

**Comment by zhenfeng-zhu** [comment]
第一篇：snippet简介和使用

1. snippet架构
2. snippet基本结构
    1. 函数
    2. 模块
    3. 使用components
3. 如何调用
4. 当前soulcard使用的snippet

第二篇：Fetcher

1. Fetcher的功能简介
2. SpeedRunFetcher
    1. 请求流图
    2. 源码分析
    3. 如何使用

第三篇：Manager

1. Manager类snippet简介
2. UserManager
    1. 请求流图
    2. 源码分析
    3. 如何使用
3. TemplateManager
    1. 请求流图
    2. 源码分析
    3. 如何使用
    

第四篇：Render

1. Render类功能简介
2. SounlCardRender
    1. 请求流图
    2. 源码分析
        1. 第一步
        2. 。。。
    3. 如何使用
3. SoulCardRenderLive
    1. 请求流图
    2. 源码分析
        1. 第一步
        2. 第二步
        3. 。。。
    3. 如何使用
