### ISSUE TITLE
用 Elixir 重写 HTML

### ISSUE THREAD

**Issue by Dream4ever** [WeLightProject/Tai-Shang-Soul-Card#49]
Money: `800R`

1. 将纯 HTML + CSS + JS 的 [HTML 页面](https://gist.github.com/Dream4ever/eef88b4b16a0f9cb97cd0ad969c1bfd3) 中的动态信息用 Elixir 进行重写，可参照 Gist：https://gist.github.com/leeduckgo/1a301c084577fde54df73ced3139a3cb 。
2. 输出一篇文章，以本次需求为例，说清楚如何把普通 HTML 转化为Elixir LiveView HTML。

**Comment by zhenfeng-zhu** [comment]
举手！

**Comment by leeduckgo** [comment]
closed because using the frontend render now.
